[tool.poetry]
name = "mlencrypt-research"
version = "0.1.0"
description = "Hyperparameter Optimization of Tree Parity Machines to Minimize the Effectiveness of Unconventional Attacks on Neural Cryptography​."
authors = ["sumanthratna <sumanthratna@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.18.2"
seaborn = "^0.10.0"
torch = "^1.4.0"
tensorflow = "^2.1.0"
tensorflow-estimator = "2.1.0"
setuptools = "41.0.0"
hyperopt = "^0.2.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
